[programs.devnet]
punky_staking = "FVNtaSsr1P2zJ7v5ypCuynySFzaX9cUn7FyWJ6V3kMMH"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/opt/Soldev/keypair/devnet-ApyraDev.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
